### ISSUE TITLE
Unable to maximize vm to full screen

### ISSUE THREAD

**Issue by AathiraKrishna** [EtricKombat/KOBDevOps#15]
Steps to reproduce:
From Ubuntu-Oracle VM VirtualBox window
Click on Devices-->Click on Insert Guest Additions CD Image
Error pop-up window displayed as below:
![vm error](https://user-images.githubusercontent.com/55534174/67863585-2ea18600-fb4a-11e9-979a-ef528a07aa95.png)

**Comment by EtricKombat** [comment]
Try referencing out the steps mentioned in this forum:

https://askubuntu.com/questions/505805/unable-to-have-full-screen-ubuntu-in-virtualbox

**Comment by EtricKombat** [comment]
Closing .
If still not able to resolve..either re-open this issue or re-create a Ubuntu Virtual Machine freshly from ISO .
