### ISSUE TITLE
Bugs 2 : Could not get lock /var/lib/apt/lists/lock

### ISSUE THREAD

**Issue by EtricKombat** [EtricKombat/KOBDevOps#2]
![issue](https://user-images.githubusercontent.com/33585301/66981850-98457d00-f0d2-11e9-9da6-69babc202a13.JPG)
**Issue 2 :** 

       #sudo apt-get update -y

       Reading package lists... Done
       E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
       E: Unable to lock directory /var/lib/apt/lists/

**Comment by EtricKombat** [comment]
![Solution](https://user-images.githubusercontent.com/33585301/66989133-67207900-f0e1-11e9-9d01-06bb380c76e0.JPG)
**Solution :**

       #lsof /var/lib/apt/lists/lock

       lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1000/gvfs
      Output information may be incomplete.

**Comment by AathiraKrishna** [comment]
Please refer the below screenshot for the related issue observed

**Comment by AathiraKrishna** [comment]
![update error](https://user-images.githubusercontent.com/55534174/68913656-0d63ab00-0782-11ea-89ad-7332425f7c23.PNG)

**Comment by EtricKombat** [comment]
Hi Athira,
The is being caused because the user doesn't have privileges to perform this actions.

### Solution
          sudo lsof /var/lib/apt/lists/lock
          sudo kill -9 [process_id]

**Comment by AathiraKrishna** [comment]
Thanks Eric

**Comment by AathiraKrishna** [comment]
I tried the command sudo kill -9 [process_id] but it states "failed to parse argument process_id"/
Please refer the screenshot attached.
![permission denied error](https://user-images.githubusercontent.com/55534174/68952459-e4750180-07e5-11ea-96f6-5f1d0f7c944a.PNG)

**Comment by EtricKombat** [comment]
Ok...lets do a reboot and start fresh by trying out the listed command:
  
        sudo reboot

![snapshot](https://user-images.githubusercontent.com/33585301/68958304-d7f6a600-07f1-11ea-8dcb-f8ee334420c6.JPG)


Once the machine is restarted , try the update command one more time..

**Comment by AathiraKrishna** [comment]
Both update and upgrade were successful after the reboot.
Followed the following commands after reboot.
sudo su
Gave password
apt-get update -y
apt-get upgrade -y

**Comment by EtricKombat** [comment]
Now you can try out the manual steps mentioned in below listed link:

        https://github.com/EtricKombat/KOBDevOps/blob/master/docs/02_ManuelSteps.md
