### ISSUE TITLE
Output of VON Network Setting up not as expected

### ISSUE THREAD

**Issue by AathiraKrishna** [EtricKombat/KOBDevOps#22]
Steps followed:
1) Ran the manual steps for Setting up the VON Network
2) Entered the url http://localhost:9000 in Firefox browser in VM

Actual Result:
The browser displays the message "Error initializing pool ledger"
Expected Result:
All four nodes should be displayed

Please refer the screenshot attached

**Comment by AathiraKrishna** [comment]
![VON_ERROR](https://user-images.githubusercontent.com/55534174/69077820-81d96b00-0a5c-11ea-9247-6d4c31900331.PNG)
![VON_COMMAND_TERMINAL](https://user-images.githubusercontent.com/55534174/69077878-a9303800-0a5c-11ea-8356-077af66a32e0.PNG)

**Comment by EtricKombat** [comment]
Hi Athira, 
-The terminal seems to be listing down with expected output.
-I just ran this in my system and the nodes are up and running for me

Resolution:1
- please create a new (or  clone of) VM and try to repeat the steps

Resolution : 2
Try out the automated script by performing the listed steps:

        git clone https://github.com/EtricKombat/KOBDevOps.git 
        cd KOBDevOps/
        ./KOBSetup.sh
        KOB install KOBVON

**Comment by EtricKombat** [comment]
Closing this issue as this has been opened for 18+ days without any responds.
Feel free to re-open and posting issue relating the same.

**Comment by mohitrakhade20** [comment]
I am running this on my localmachine, how to resolve it? I don't want to create  another VM

**Comment by mohitrakhade20** [comment]
It worked for me, I cloned and run again. Can I know why that error was bugging?

**Comment by EtricKombat** [comment]
Hi @mohitrakhade20 , this usually happens when the initial ledger gets configured not properly. This is not the official repository of our opensource project. If you could please this dicussion on our official namespace (forked from bcgov )  https://github.com/hyperledgerkochi/von-network

**Comment by EtricKombat** [comment]
@mohitrakhade20 , if you are interested to learn more about how we intent to use hyperledger indy/ Aries ♈ , you should definitly join our KochiOrgBook's Whatsapp group for having any open discussions https://chat.whatsapp.com/El6d3aAc6pYLEDEdQPVABY
