### ISSUE TITLE
Bugs 5: git : Depends : liberror-perl but it is not installable

### ISSUE THREAD

**Issue by EtricKombat** [EtricKombat/KOBDevOps#5]
![issue](https://user-images.githubusercontent.com/33585301/66996177-e025cd80-f0ed-11e9-8087-941e35458832.JPG)
**Issue  :**

      GIT not able to install   
![GIT--ERROR](https://user-images.githubusercontent.com/33585301/66996346-35fa7580-f0ee-11e9-9581-e2c7a477a8bc.JPG)

**Comment by EtricKombat** [comment]
![Solution](https://user-images.githubusercontent.com/33585301/66996472-66421400-f0ee-11e9-9636-ea138c0a3e38.JPG)
**Solution :**

This can be solved by 

* updating the /etc/apt/apt.conf file with necessary proxy settings [refer :Issue 4]
* update the system with "sudo apt-get update -y"
* try again to install git using "sudo apt install git"

**Comment by Marchee72** [comment]
soltuon not working on ubuntu 21.10

**Comment by JEHER** [comment]
The update of the  #sudo /etc/apt/apt.con  solution worked.

**Comment by ZainKizilbash** [comment]
give me command
